DROP DATABASE IF EXISTS LAIKA;

CREATE DATABASE LAIKA;

USE LAIKA;

CREATE TABLE usuarios(
	IDUSUARIO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	USUARIO VARCHAR(30) NOT NULL UNIQUE,
	CLAVE VARCHAR(32) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE generos(
	IDGENERO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GENERO VARCHAR(30) UNIQUE NOT NULL
)ENGINE=InnoDB;

CREATE TABLE autores(
	IDAUTOR INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AUTOR VARCHAR(30) UNIQUE NOT NULL
)ENGINE=InnoDB;

CREATE TABLE libros(
	IDLIBRO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITULO VARCHAR(50) NOT NULL,
	ANIO YEAR NOT NULL,
	DESCRIPCION TEXT(500) NOT NULL,
	FKAUTORES INT UNSIGNED,
	FKGENEROS INT UNSIGNED,
	
	FOREIGN KEY(FKAUTORES) REFERENCES autores(IDAUTOR) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FKGENEROS) REFERENCES generos(IDGENERO) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE comentarios(
	IDCOMENTARIO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	COMENTARIO VARCHAR(50) NOT NULL,
	FECHA datetime NOT NULL,
	FKUSUARIOS INT UNSIGNED,
	FKLIBROS INT UNSIGNED,

	FOREIGN KEY(FKUSUARIOS) REFERENCES usuarios(IDUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FKLIBROS) REFERENCES libros(IDLIBRO) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE usuario_has_fav (
	FKUSUARIO INT UNSIGNED,
	FKUSUARIOFAV INT UNSIGNED,

	FOREIGN KEY(FKUSUARIO) REFERENCES usuarios(IDUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FKUSUARIOFAV) REFERENCES usuarios(IDUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT IDFAV UNIQUE (FKUSUARIO,FKUSUARIOFAV);
)ENGINE=InnoDB;

CREATE TABLE usuario_has_libro (
	FKUSUARIO INT UNSIGNED,
	FKLIBRO INT UNSIGNED,

	FOREIGN KEY(FKUSUARIO) REFERENCES usuarios(IDUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FKLIBRO) REFERENCES libros(IDLIBRO) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT IDFAV UNIQUE (FKUSUARIO,FKLIBRO);
)ENGINE=InnoDB;

CREATE TABLE notificaciones (
	IDNOTIFICACION INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FKUSUARIO INT UNSIGNED,
	FKLIBRO INT UNSIGNED,
	NOTIFICACION VARCHAR(100) UNSIGNED,
	LEIDO BOOLEAN DEFAULT 0,

	FOREIGN KEY(FKUSUARIO) REFERENCES usuarios(IDUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FKLIBRO) REFERENCES libros(IDLIBRO) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;